language: cpp
compiler:
    - gcc
    - clang
branches:
   only:
    - master
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libeigen3-dev libarpack2-dev cmake
    - wget http://googletest.googlecode.com/files/gtest-1.6.0.zip
    - unzip -q gtest-1.6.0.zip
    - cd gtest-1.6.0
    - cmake . && make
    - cd ..
    - cmake -DBUILD_TESTS=1
script: make
after_script: make test
#env:
#    matrix:
#        - CMAKE_BUILD_TYPE=Debug
#        - CMAKE_BUILD_TYPE=Release
notifications:
    email:
        on_failure: always
