language: cpp
compiler:
    - gcc
    - clang
branches:
   only:
    - master
notifications:
    email: false
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libeigen3-dev libarpack2-dev cmake
script:
    - mkdir build && cd build && cmake -DBUILD_TESTS=1 .. && ctest -VV
