language: cpp
compiler:
    - gcc
    - clang
branches:
   only:
    - master
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libeigen3-dev libarpack2-dev cmake valgrind python-numpy
    - wget http://googletest.googlecode.com/files/gtest-1.6.0.zip
    - unzip -q gtest-1.6.0.zip
    - cd gtest-1.6.0
    - cmake . && make
    - cd ..
    - cmake -DBUILD_TESTS=1
script: make
after_script: make test
after_success:
    - python test/generate_swissroll.py 100
    - CALLENV='valgrind --leak-check=full --xml=yes --xml-file=/dev/stdout' TAPKEE_ELF=bin/tapkee INPUT_FILE=input.dat OUTPUT_FILE=/dev/null ./test/valgrind_run_all.sh |
      xsltproc test/valgrind_tests_transformer.xslt /dev/stdin
notifications:
    email:
        on_failure: always
